Fixes the thumbnail loading for animated stickers and emojis.
An error occurs during the channel thumbnail loading if an animated sticker or emoji is set as the cover:
```
Traceback (most recent call last):
  File "/app/telegram/channels.py", line 145, in get_channel_photo
    local_file = await client.download_profile_photo(chat, '/tmp/%s' % hash, download_big=is_large)
  File "/usr/local/lib/python3.7/site-packages/telethon/client/downloads.py", line 265, in download_profile_photo
    thumb=thumb, progress_callback=None
  File "/usr/local/lib/python3.7/site-packages/telethon/client/downloads.py", line 832, in _download_photo
    file_size = size.size
AttributeError: 'VideoSizeStickerMarkup' object has no attribute 'size'
```
These types should be ignored during the thumbnail search.